### ISSUE TITLE
dxf list-aliases returns TypeError if no tags are available

### ISSUE THREAD

**Issue by mrueg** [davedoesdev/dxf#18]
Minimal example
```
./ubuntu
./ubuntu/_uploads
./ubuntu/_layers
./ubuntu/_layers/sha256
./ubuntu/_layers/sha256/REDACTED
./ubuntu/_manifests
./ubuntu/_manifests/revisions
./ubuntu/_manifests/revisions/sha256
./ubuntu/_manifests/revisions/sha256/REDACTED
./ubuntu/_manifests/tags
```

```
$ dxf list-aliases foo/ubuntu
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.5/dxf", line 11, in <module>
    load_entry_point('python-dxf==7.1.0', 'console_scripts', 'dxf')()
  File "/usr/lib64/python3.5/site-packages/dxf/main.py", line 206, in main
    exit(doit(sys.argv[1:], os.environ))
  File "/usr/lib64/python3.5/site-packages/dxf/main.py", line 193, in doit
    _doit()
  File "/usr/lib64/python3.5/site-packages/dxf/main.py", line 185, in _doit
    for name in dxf_obj.list_aliases(iterate=True):
  File "/usr/lib64/python3.5/site-packages/dxf/__init__.py", line 134, in __iter__
    for v in response.json()[self._header]:
TypeError: 'NoneType' object is not iterable
```

**Comment by davedoesdev** [comment]
@mrueg  Thanks! I didn't realise the tags list in the JSON could be null. Would have made more sense to be any empty list.

Anyway, would you please try version 7.1.1?

**Comment by mrueg** [comment]
Thanks for the quick fix!
