### ISSUE TITLE
"dxf get-digest" doesn't work with multi-arch images

### ISSUE THREAD

**Issue by ghost** [davedoesdev/dxf#47]
`get-digest` on single-arch images work fine:
```
$ DXF_HOST=registry-1.docker.io dxf get-digest ubuntu 12.04
sha256:5b117edd0b767986092e9f721ba2364951b0a271f53f1f41aff9dd1861c2d4fe
```

But multi-arch images fail with `KeyError: 'config'`:
```
$ DXF_HOST=registry-1.docker.io dxf get-digest ubuntu 22.04
Traceback (most recent call last):
  File "/home/behlers/.local/pyvenv/dxf/bin/dxf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/behlers/.local/pyvenv/dxf/lib/python3.11/site-packages/dxf/main.py", line 219, in main
    sys.exit(doit(sys.argv[1:], os.environ))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/behlers/.local/pyvenv/dxf/lib/python3.11/site-packages/dxf/main.py", line 206, in doit
    _doit()
  File "/home/behlers/.local/pyvenv/dxf/lib/python3.11/site-packages/dxf/main.py", line 189, in _doit
    dgsts = [dxf_obj.get_digest(name) for name in args.args]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/behlers/.local/pyvenv/dxf/lib/python3.11/site-packages/dxf/main.py", line 189, in <listcomp>
    dgsts = [dxf_obj.get_digest(name) for name in args.args]
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/behlers/.local/pyvenv/dxf/lib/python3.11/site-packages/dxf/__init__.py", line 723, in get_digest
    return self._get_alias(alias, manifest, verify, False, True, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/behlers/.local/pyvenv/dxf/lib/python3.11/site-packages/dxf/__init__.py", line 661, in _get_alias
    dgst = parsed_manifest['config']['digest']
           ~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'config'
```

The reason is, that multi-arch images return a manifest list, that contains just a list of architectures with a specific manifest digest for each architecture. Getting this manifest reveals the needed information:
```
$ docker buildx imagetools inspect --raw ubuntu:22.04 | jq
{
  "manifests": [
    {
      "digest": "sha256:7a57c69fe1e9d5b97c5fe649849e79f2cfc3bf11d10bbd5218b4eb61716aebe6",
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      },
      "size": 424
    },
    {
      "digest": "sha256:ad18cfdb19dac67bf0072dacea661a817330e5c955d081f4d09914e743ae5d4a",
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "platform": {
        "architecture": "arm",
        "os": "linux",
        "variant": "v7"
      },
      "size": 424
    },
    {
      "digest": "sha256:537da24818633b45fcb65e5285a68c3ec1f3db25f5ae5476a7757bc8dfae92a3",
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "platform": {
        "architecture": "arm64",
        "os": "linux",
        "variant": "v8"
      },
      "size": 424
    },
    {
      "digest": "sha256:f23b7ade9f88f91c8d5932a48b721712ed509a607d9a05cdeae4cd06de09e5f7",
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "platform": {
        "architecture": "ppc64le",
        "os": "linux"
      },
      "size": 424
    },
    {
      "digest": "sha256:b351315d950a4da70f19d62f4da5dd7f9a445eb8c8d6851a5b6cdddbdafb13cf",
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "platform": {
        "architecture": "s390x",
        "os": "linux"
      },
      "size": 424
    }
  ],
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "schemaVersion": 2
}
$
$
$ docker buildx imagetools inspect --raw ubuntu@sha256:7a57c69fe1e9d5b97c5fe649849e79f2cfc3bf11d10bbd5218b4eb61716aebe6 | jq
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "size": 2298,
    "digest": "sha256:08d22c0ceb150ddeb2237c5fa3129c0183f3cc6f5eeb2e7aa4016da3ad02140a"
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
      "size": 29533950,
      "digest": "sha256:2ab09b027e7f3a0c2e8bb1944ac46de38cebab7145f0bd6effebfe5492c818b6"
    }
  ]
}
```

**Comment by davedoesdev** [comment]
@b-ehlers thanks for this. I'll take a look and see what I can do.
I didn't intend dxf to be used with docker images, however.

**Comment by davedoesdev** [comment]
If there is an image per arch, what should get_digest return do you think?
A dict of config hashes for each arch?

**Comment by davedoesdev** [comment]
Or perhaps both. If not specified, returns all as a dict, otherwise it narrows

**Comment by davedoesdev** [comment]
@b-ehlers this is now on the `multi-arch` branch. I need to write some tests before merging.
